name: gnome-logs
version: 3.28.0
summary: A log viewer for the systemd journal
description: |
  Logs makes it easy to view and filter log messages and events.
  Filter logs by category and importance to get the information you want. Use
  the integrated search to get more relevant results.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-logs:
    interface: dbus
    bus: session
    name: org.gnome.Logs

apps:
  gnome-logs:
    command: desktop-launch gnome-logs
    plugs:
      - log-observe
      - desktop
      - desktop-legacy
      - network
      - home
      - gsettings
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Logs.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-logs

parts:
  libsystemd:
    after: [desktop-gnome-platform]
    source: https://github.com/systemd/systemd
    source-type: git
    #source-branch: master
    source-tag: v232
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/usr, --disable-tests, --disable-maintainer-mode, --disable-dependency-tracking, --disable-man, --disable-appstream-util]
    organize:
      snap/gnome-logs/current/usr: usr
    build-packages:
      - pkg-config
      - xsltproc
      - docbook-xsl
      - docbook-xml
      - m4
      - intltool
      - gperf
      - gnu-efi
      - libcap-dev
      - libpam0g-dev
      - libapparmor-dev
      - libidn11-dev
      - iptables-dev
      - libaudit-dev
      - libdbus-1-dev
      - libcryptsetup-dev
      - libselinux1-dev
      - libacl1-dev
      - liblzma-dev
      - liblz4-dev
      - liblz4-tool
      - libbz2-dev
      - zlib1g-dev
      - libcurl4-gnutls-dev
      - libmicrohttpd-dev
      - libgnutls28-dev
      - libgcrypt20-dev
      - libkmod-dev
      - libblkid-dev
      - libmount-dev
      - libseccomp-dev
      - libdw-dev
      - libpolkit-gobject-1-dev
      - linux-base
      - acl
      - python3
      - python3-lxml
      - python3-pyparsing
      - tzdata
      - libcap2-bin
      - iproute2

  gnome-logs:
    after: [libsystemd]
    source: https://git.gnome.org/browse/gnome-logs
    source-type: git
    source-tag: gnome-logs-3.28.0
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-logs/current/usr]
    organize:
      snap/gnome-logs/current/usr: usr
    prepare:
      sed -i.bak -e 's|=gnome-logs$|=${SNAP}/meta/gui/gnome-logs.png|g' data/org.gnome.Logs.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/512x512/gnome-logs.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - appstream-util
      - desktop-file-utils
      - gnome-common
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - yelp-tools

  libraries:
    plugin: nil
    prime:
      - "-*"
