name: gnome-logs
adopt-info: gnome-logs
summary: A log viewer for the systemd journal
description: |
  Logs makes it easy to view and filter log messages and events.
  Filter logs by category and importance to get the information you want. Use
  the integrated search to get more relevant results.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

slots:
  # for GtkApplication registration
  gnome-logs:
    interface: dbus
    bus: session
    name: org.gnome.Logs

apps:
  gnome-logs:
    extensions: [gnome-3-34]
    command: desktop-launch gnome-logs
    plugs:
      - log-observe
      - network
      - home
    desktop: usr/share/applications/org.gnome.Logs.desktop
    common-id: org.gnome.Logs.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-logs

parts:
  gnome-logs:
    source: https://gitlab.gnome.org/GNOME/gnome-logs.git
    source-type: git
    source-tag: gnome-logs-3.34.0
    plugin: meson
    meson-parameters: [--prefix=/usr]
    organize:
      snap/gnome-logs/current/usr: usr
    build-packages:
      - libsystemd-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10 | sed -e s/gnome-logs-//g)
      sed -i.bak -e 's|symlink_media: true|symlink_media: false|g' help/meson.build

  libraries:
    plugin: nil
    prime:
      - "-*"

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [libraries]
    plugin: nil
    build-snaps: [core18, gnome-3-34-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-34-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
