name: gnome-logs
version: 3.24.2
summary: A log viewer for the systemd journal
description: |
  Logs makes it easy to view and filter log messages and events.
  Filter logs by category and importance to get the information you want. Use
  the integrated search to get more relevant results.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-24-platform:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

slots:
  # for GtkApplication registration
  gnome-logs:
    interface: dbus
    bus: session
    name: org.gnome.Logs

apps:
  gnome-logs:
    command: desktop-launch gnome-logs
    plugs:
      - log-observe
      - desktop
      - desktop-legacy
      - network
      - x11
      - home
      - gsettings
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Logs.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/gnome-logs

parts:
  gnome-logs:
    after: [desktop-gnome-platform]
    source: https://git.gnome.org/browse/gnome-logs
    source-type: git
    #source-branch: master
    source-tag: gnome-logs-3.24.2
    plugin: autotools
    # workaround the issue described in https://launchpad.net/bugs/1583250
    configflags: [--prefix=/snap/gnome-logs/current/usr]
    organize:
      snap/gnome-logs/current/usr: usr
    prepare:
      sed -i.bak -e 's|=gnome-logs$|=${SNAP}/meta/gui/gnome-logs.png|g' data/org.gnome.Logs.desktop.in
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/512x512/gnome-logs.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - appstream-util
      - desktop-file-utils
      - gnome-common
      - gnome-pkg-tools
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libsystemd-dev
      - yelp-tools
    stage-packages:
      - libsystemd0

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
